from flask import Flask, jsonify
from flask_cors import CORS

app = Flask(__name__)
cors = CORS(app, resources={r"*": {"origins": "*"}})

database = {
    'Selecione a Operação': [
        {'de': 'Circ.Susep360', 'para': 'BaseOperacional', 'id': '', 'grupo': 'Selecione a Operação'},

    ],
    'Premit': [
        {'de': 'SEQUENCIA', 'para': '', 'id': '', 'grupo': 'premit'},
        {'de': 'COD_CIA', 'para': '', 'id': '', 'grupo': 'premit'},
        {'de': 'NUM_PROC', 'para': '', 'id': '', 'grupo': 'premit'},
        {'de': 'DT_BASE', 'para': '', 'id': '', 'grupo': 'premit'},
        {'de': 'TIPO_MOV', 'para': '', 'id': '', 'grupo': 'premit'},
        {'de': 'UF_DEP', 'para': '', 'id': '', 'grupo': 'premit'},
        {'de': 'UF_RISCO', 'para': '', 'id': '', 'grupo': 'premit'},
        {'de': 'COD_RAMO', 'para': '', 'id': '', 'grupo': 'premit'},
        {'de': 'NUM_APOL', 'para': '', 'id': '', 'grupo': 'premit'},
        {'de': 'NUM_END', 'para': '', 'id': '', 'grupo': 'premit'},
        {'de': 'NUM_PROP', 'para': '', 'id': '', 'grupo': 'premit'},
        {'de': 'DT_PROP', 'para': '', 'id': '', 'grupo': 'premit'},
        {'de': 'CPF_SEG', 'para': '', 'id': '', 'grupo': 'premit'},
        {'de': 'QTD_SEG', 'para': '', 'id': '', 'grupo': 'premit'},
        {'de': 'CPF_TOM', 'para': '', 'id': '', 'grupo': 'premit'},
        {'de': 'QTD_TOM', 'para': '', 'id': '', 'grupo': 'premit'},
        {'de': 'DT_EMIS', 'para': '', 'id': '', 'grupo': 'premit'},
        {'de': 'DT_INI_VIG', 'para': '', 'id': '', 'grupo': 'premit'},
        {'de': 'DT_FIM_VIG', 'para': '', 'id': '', 'grupo': 'premit'},
        {'de': 'PR_EMIT', 'para': '', 'id': '', 'grupo': 'premit'},
        {'de': 'PR_COS_CED', 'para': '', 'id': '', 'grupo': 'premit'},
        {'de': 'AD_FRAC', 'para': '', 'id': '', 'grupo': 'premit'},
        {'de': 'CUST_APOL', 'para': '', 'id': '', 'grupo': 'premit'},
        {'de': 'IOF', 'para': '', 'id': '', 'grupo': 'premit'},
        {'de': 'COMIS', 'para': '', 'id': '', 'grupo': 'premit'},
        {'de': 'COMIS_COSS', 'para': '', 'id': '', 'grupo': 'premit'},
        {'de': 'PRO_LAB', 'para': '', 'id': '', 'grupo': 'premit'},
        {'de': 'CPF_ESTIP', 'para': '', 'id': '', 'grupo': 'premit'},
        {'de': 'IS', 'para': '', 'id': '', 'grupo': 'premit'},

    ],
    'Premac': [
        {'de': 'SEQUENCIA', 'para': '', 'id': '', 'grupo': 'premac'},
        {'de': 'COD_CIA', 'para': '', 'id': '', 'grupo': 'premac'},
        {'de': 'NUM_PROC', 'para': '', 'id': '', 'grupo': 'premac'},
        {'de': 'DT_BASE', 'para': '', 'id': '', 'grupo': 'premac'},
        {'de': 'TIPO_MOV', 'para': '', 'id': '', 'grupo': 'premac'},
        {'de': 'UF_DEP', 'para': '', 'id': '', 'grupo': 'premac'},
        {'de': 'UF_RISCO', 'para': '', 'id': '', 'grupo': 'premac'},
        {'de': 'COD_RAMO', 'para': '', 'id': '', 'grupo': 'premac'},
        {'de': 'NUM_APOL', 'para': '', 'id': '', 'grupo': 'premac'},
        {'de': 'NUM_END', 'para': '', 'id': '', 'grupo': 'premac'},
        {'de': 'COD_COSS', 'para': '', 'id': '', 'grupo': 'premac'},
        {'de': 'DT_EMIS', 'para': '', 'id': '', 'grupo': 'premac'},
        {'de': 'DT_INI_VIG', 'para': '', 'id': '', 'grupo': 'premac'},
        {'de': 'DT_FIM_VIG', 'para': '', 'id': '', 'grupo': 'premac'},
        {'de': 'PR_COSS_AC', 'para': '', 'id': '', 'grupo': 'premac'},
        {'de': 'COM_COS_AC', 'para': '', 'id': '', 'grupo': 'premac'},

    ],
    'Premced': [
        {'de': 'SEQUENCIA', 'para': '', 'id': '', 'grupo': 'premced'},
        {'de': 'COD_CIA', 'para': '', 'id': '', 'grupo': 'premced'},
        {'de': 'COD_COSS', 'para': '', 'id': '', 'grupo': 'premced'},
        {'de': 'NUM_PROC', 'para': '', 'id': '', 'grupo': 'premced'},
        {'de': 'DT_BASE', 'para': '', 'id': '', 'grupo': 'premced'},
        {'de': 'TIPO_MOV', 'para': '', 'id': '', 'grupo': 'premced'},
        {'de': 'NUM_APOL', 'para': '', 'id': '', 'grupo': 'premced'},
        {'de': 'NUM_END', 'para': '', 'id': '', 'grupo': 'premced'},
        {'de': 'NUM_PROP', 'para': '', 'id': '', 'grupo': 'premced'},
        {'de': 'PR_COS_CED', 'para': '', 'id': '', 'grupo': 'premced'},
        {'de': 'COMIS_COSS', 'para': '', 'id': '', 'grupo': 'premced'},
        {'de': '_CED', 'para': '', 'id': '', 'grupo': 'premced'},

    ],
    'Premrec': [
        {'de': 'SEQUENCIA', 'para': '', 'id': '', 'grupo': 'premrec'},
        {'de': 'COD_CIA', 'para': '', 'id': '', 'grupo': 'premrec'},
        {'de': 'DT_BASE', 'para': '', 'id': '', 'grupo': 'premrec'},
        {'de': 'TIPO_MOV', 'para': '', 'id': '', 'grupo': 'premrec'},
        {'de': 'COD_RAMO', 'para': '', 'id': '', 'grupo': 'premrec'},
        {'de': 'NUM_APOL', 'para': '', 'id': '', 'grupo': 'premrec'},
        {'de': 'NUM_END', 'para': '', 'id': '', 'grupo': 'premrec'},
        {'de': 'NUM_PROP', 'para': '', 'id': '', 'grupo': 'premrec'},
        {'de': 'DT_PROP', 'para': '', 'id': '', 'grupo': 'premrec'},
        {'de': 'PRESTACAO', 'para': '', 'id': '', 'grupo': 'premrec'},
        {'de': 'QTDE_PREST', 'para': '', 'id': '', 'grupo': 'premrec'},
        {'de': 'DT_EMIS_PRE', 'para': '', 'id': '', 'grupo': 'premrec'},
        {'de': 'DT_VEN_PRE', 'para': '', 'id': '', 'grupo': 'premrec'},
        {'de': 'DT_INI_VIG', 'para': '', 'id': '', 'grupo': 'premrec'},
        {'de': 'DT_FIM_VIG', 'para': '', 'id': '', 'grupo': 'premrec'},
        {'de': 'PR_EMIT', 'para': '', 'id': '', 'grupo': 'premrec'},
        {'de': 'PERC_COSS', 'para': '', 'id': '', 'grupo': 'premrec'},
        {'de': 'AD_FRAC', 'para': '', 'id': '', 'grupo': 'premrec'},
        {'de': 'CUST_APOL', 'para': '', 'id': '', 'grupo': 'premrec'},
        {'de': 'IOF', 'para': '', 'id': '', 'grupo': 'premrec'},
        {'de': 'OFER', 'para': '', 'id': '', 'grupo': 'premrec'},

    ],
    'Premrecac': [
        {'de': 'SEQUENCIA', 'para': '', 'id': '', 'grupo': 'premrecac'},
        {'de': 'COD_CIA', 'para': '', 'id': '', 'grupo': 'premrecac'},
        {'de': 'DT_BASE', 'para': '', 'id': '', 'grupo': 'premrecac'},
        {'de': 'TIPO_MOV', 'para': '', 'id': '', 'grupo': 'premrecac'},
        {'de': 'COD_RAMO', 'para': '', 'id': '', 'grupo': 'premrecac'},
        {'de': 'NUM_APOL', 'para': '', 'id': '', 'grupo': 'premrecac'},
        {'de': 'NUM_END', 'para': '', 'id': '', 'grupo': 'premrecac'},
        {'de': 'COD_COSS', 'para': '', 'id': '', 'grupo': 'premrecac'},
        {'de': 'PRESTACAO', 'para': '', 'id': '', 'grupo': 'premrecac'},
        {'de': 'QTDE_PREST', 'para': '', 'id': '', 'grupo': 'premrecac'},
        {'de': 'DT_EMIS_PRE', 'para': '', 'id': '', 'grupo': 'premrecac'},
        {'de': 'DT_VEN_PRE', 'para': '', 'id': '', 'grupo': 'premrecac'},
        {'de': 'DT_INI_VIG', 'para': '', 'id': '', 'grupo': 'premrecac'},
        {'de': 'DT_FIM_VIG', 'para': '', 'id': '', 'grupo': 'premrecac'},
        {'de': 'PR_COSS_AC', 'para': '', 'id': '', 'grupo': 'premrecac'},

    ],
    'Premreceb': [
        {'de': 'SEQUENCIA', 'para': '', 'id': '', 'grupo': 'premreceb'},
        {'de': 'COD_CIA', 'para': '', 'id': '', 'grupo': 'premreceb'},
        {'de': 'DT_BASE', 'para': '', 'id': '', 'grupo': 'premreceb'},
        {'de': 'TIPO_MOV', 'para': '', 'id': '', 'grupo': 'premreceb'},
        {'de': 'COD_RAMO', 'para': '', 'id': '', 'grupo': 'premreceb'},
        {'de': 'NUM_APOL', 'para': '', 'id': '', 'grupo': 'premreceb'},
        {'de': 'NUM_END', 'para': '', 'id': '', 'grupo': 'premreceb'},
        {'de': 'NUM_PROP', 'para': '', 'id': '', 'grupo': 'premreceb'},
        {'de': 'DT_PROP', 'para': '', 'id': '', 'grupo': 'premreceb'},
        {'de': 'PRESTACAO', 'para': '', 'id': '', 'grupo': 'premreceb'},
        {'de': 'DT_REC_PRE', 'para': '', 'id': '', 'grupo': 'premreceb'},
        {'de': 'DT_VEN_PRE', 'para': '', 'id': '', 'grupo': 'premreceb'},
        {'de': 'NUM_BAN', 'para': '', 'id': '', 'grupo': 'premreceb'},
        {'de': 'CNPJ_BAN', 'para': '', 'id': '', 'grupo': 'premreceb'},
        {'de': 'NUM_BOL', 'para': '', 'id': '', 'grupo': 'premreceb'},
        {'de': 'NUM_DOC', 'para': '', 'id': '', 'grupo': 'premreceb'},
        {'de': 'NUM_AGE', 'para': '', 'id': '', 'grupo': 'premreceb'},
        {'de': 'NUM_NOS', 'para': '', 'id': '', 'grupo': 'premreceb'},
        {'de': 'VAL_DOC', 'para': '', 'id': '', 'grupo': 'premreceb'},
        {'de': 'VAL_DESC', 'para': '', 'id': '', 'grupo': 'premreceb'},
        {'de': 'VAL_MUL', 'para': '', 'id': '', 'grupo': 'premreceb'},
        {'de': 'VAL_COB', 'para': '', 'id': '', 'grupo': 'premreceb'},

    ],
    'Premrecec': [
        {'de': 'SEQUENCIA', 'para': '', 'id': '', 'grupo': 'Premrecec'},
        {'de': 'COD_CIA', 'para': '', 'id': '', 'grupo': 'Premrecec'},
        {'de': 'DT_BASE', 'para': '', 'id': '', 'grupo': 'Premrecec'},
        {'de': 'TIPO_MOV', 'para': '', 'id': '', 'grupo': 'Premrecec'},
        {'de': 'COD_RAMO', 'para': '', 'id': '', 'grupo': 'Premrecec'},
        {'de': 'NUM_APOL', 'para': '', 'id': '', 'grupo': 'Premrecec'},
        {'de': 'NUM_END', 'para': '', 'id': '', 'grupo': 'Premrecec'},
        {'de': 'NUM_PROP', 'para': '', 'id': '', 'grupo': 'Premrecec'},
        {'de': 'DT_PROP', 'para': '', 'id': '', 'grupo': 'Premrecec'},
        {'de': 'PRESTACAO', 'para': '', 'id': '', 'grupo': 'Premrecec'},
        {'de': 'DT_REC_PRE', 'para': '', 'id': '', 'grupo': 'Premrecec'},
        {'de': 'DT_VEN_PRE', 'para': '', 'id': '', 'grupo': 'Premrecec'},
        {'de': 'TIPO_REC', 'para': '', 'id': '', 'grupo': 'Premrecec'},
        {'de': 'NUM_BAN_SEG', 'para': '', 'id': '', 'grupo': 'Premrecec'},
        {'de': 'NUM_AGE_SEG', 'para': '', 'id': '', 'grupo': 'Premrecec'},
        {'de': 'NUM_CON_SEG', 'para': '', 'id': '', 'grupo': 'Premrecec'},
        {'de': 'NUM_BAN', 'para': '', 'id': '', 'grupo': 'Premrecec'},
        {'de': 'NUM_AGE', 'para': '', 'id': '', 'grupo': 'Premrecec'},
        {'de': 'NUM_CON', 'para': '', 'id': '', 'grupo': 'Premrecec'},
        {'de': 'VAL_COB', 'para': '', 'id': '', 'grupo': 'Premrecec'},

    ],
    'Recprovb': [
        {'de': 'SEQUENCIA', 'para': '', 'id': '', 'grupo': 'Recprovb'},
        {'de': 'COD_CIA', 'para': '', 'id': '', 'grupo': 'Recprovb'},
        {'de': 'DT_BASE', 'para': '', 'id': '', 'grupo': 'Recprovb'},
        {'de': 'COD_RAMO', 'para': '', 'id': '', 'grupo': 'Recprovb'},
        {'de': 'NUM_PROP', 'para': '', 'id': '', 'grupo': 'Recprovb'},
        {'de': 'DT_PROP', 'para': '', 'id': '', 'grupo': 'Recprovb'},
        {'de': 'DT_REC_PRE', 'para': '', 'id': '', 'grupo': 'Recprovb'},
        {'de': 'NUM_BAN', 'para': '', 'id': '', 'grupo': 'Recprovb'},
        {'de': 'CNPJ_BAN', 'para': '', 'id': '', 'grupo': 'Recprovb'},
        {'de': 'NUM_BOL', 'para': '', 'id': '', 'grupo': 'Recprovb'},
        {'de': 'NUM_DOC', 'para': '', 'id': '', 'grupo': 'Recprovb'},
        {'de': 'NUM_AGE', 'para': '', 'id': '', 'grupo': 'Recprovb'},
        {'de': 'NUM_NOS', 'para': '', 'id': '', 'grupo': 'Recprovb'},
        {'de': 'VAL_DOC', 'para': '', 'id': '', 'grupo': 'Recprovb'},
        {'de': 'VAL_DESC', 'para': '', 'id': '', 'grupo': 'Recprovb'},
        {'de': 'VAL_MUL', 'para': '', 'id': '', 'grupo': 'Recprovb'},
        {'de': 'VAL_COB', 'para': '', 'id': '', 'grupo': 'Recprovb'},
    
    ],
    'Recprovc': [
        {'de': 'SEQUENCIA', 'para': '', 'id': '', 'grupo': 'Recprovc'},
        {'de': 'COD_CIA', 'para': '', 'id': '', 'grupo': 'Recprovc'},
        {'de': 'DT_BASE', 'para': '', 'id': '', 'grupo': 'Recprovc'},
        {'de': 'COD_RAMO', 'para': '', 'id': '', 'grupo': 'Recprovc'},
        {'de': 'NUM_PROP', 'para': '', 'id': '', 'grupo': 'Recprovc'},
        {'de': 'DT_PROP', 'para': '', 'id': '', 'grupo': 'Recprovc'},
        {'de': 'DT_REC_PRE', 'para': '', 'id': '', 'grupo': 'Recprovc'},
        {'de': 'TIPO_REC', 'para': '', 'id': '', 'grupo': 'Recprovc'},
        {'de': 'NUM_BAN_SEG', 'para': '', 'id': '', 'grupo': 'Recprovc'},
        {'de': 'NUM_AGE_SEG', 'para': '', 'id': '', 'grupo': 'Recprovc'},
        {'de': 'NUM_CON_SEG', 'para': '', 'id': '', 'grupo': 'Recprovc'},
        {'de': 'NUM_BAN', 'para': '', 'id': '', 'grupo': 'Recprovc'},
        {'de': 'NUM_AGE', 'para': '', 'id': '', 'grupo': 'Recprovc'},
        {'de': 'NUM_CON', 'para': '', 'id': '', 'grupo': 'Recprovc'},
        {'de': 'VAL_COB', 'para': '', 'id': '', 'grupo': 'Recprovc'},

    ],
    'Resprem': [
        {'de': 'SEQUENCIA', 'para': '', 'id': '', 'grupo': 'Resprem'},
        {'de': 'COD_CIA', 'para': '', 'id': '', 'grupo': 'Resprem'},
        {'de': 'DT_BASE', 'para': '', 'id': '', 'grupo': 'Resprem'},
        {'de': 'TIPO_MOV', 'para': '', 'id': '', 'grupo': 'Resprem'},
        {'de': 'COD_RAMO', 'para': '', 'id': '', 'grupo': 'Resprem'},
        {'de': 'NUM_APOL', 'para': '', 'id': '', 'grupo': 'Resprem'},
        {'de': 'NUM_END', 'para': '', 'id': '', 'grupo': 'Resprem'},
        {'de': 'NUM_PROP', 'para': '', 'id': '', 'grupo': 'Resprem'},
        {'de': 'DT_PROP', 'para': '', 'id': '', 'grupo': 'Resprem'},
        {'de': 'DT_EMIS', 'para': '', 'id': '', 'grupo': 'Resprem'},
        {'de': 'DT_INI_VIG', 'para': '', 'id': '', 'grupo': 'Resprem'},
        {'de': 'DT_FIM_VIG', 'para': '', 'id': '', 'grupo': 'Resprem'},
        {'de': 'PR_EMIT', 'para': '', 'id': '', 'grupo': 'Resprem'},
        {'de': 'PR_COS_CED', 'para': '', 'id': '', 'grupo': 'Resprem'},
        {'de': 'PR_N_GANHO', 'para': '', 'id': '', 'grupo': 'Resprem'},
        {'de': 'COLET', 'para': '', 'id': '', 'grupo': 'Resprem'},
    ],
    'Respremc': [
        {'de': 'SEQUENCIA', 'para': '', 'id': '', 'grupo': 'Respremc'},
        {'de': 'COD_CIA', 'para': '', 'id': '', 'grupo': 'Respremc'},
        {'de': 'DT_BASE', 'para': '', 'id': '', 'grupo': 'Respremc'},
        {'de': 'TIPO_MOV', 'para': '', 'id': '', 'grupo': 'Respremc'},
        {'de': 'COD_RAMO', 'para': '', 'id': '', 'grupo': 'Respremc'},
        {'de': 'NUM_APOL', 'para': '', 'id': '', 'grupo': 'Respremc'},
        {'de': 'NUM_END', 'para': '', 'id': '', 'grupo': 'Respremc'},
        {'de': 'COD_COSS', 'para': '', 'id': '', 'grupo': 'Respremc'},
        {'de': 'DT_EMIS', 'para': '', 'id': '', 'grupo': 'Respremc'},
        {'de': 'DT_INI_VIG', 'para': '', 'id': '', 'grupo': 'Respremc'},
        {'de': 'DT_FIM_VIG', 'para': '', 'id': '', 'grupo': 'Respremc'},
        {'de': 'PR_COSS_AC', 'para': '', 'id': '', 'grupo': 'Respremc'},
        {'de': 'PR_N_GANHO', 'para': '', 'id': '', 'grupo': 'Respremc'},

    ]

}

@app.route('/<string:idx>')
def index(idx):
    return jsonify(database[idx])

if(__name__ == '__main__'):
    app.run('localhost', 5000, True)